title: <p align="center"> Vitor Lemos </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vitorgamalemos/">LinkedIn</a> |
  <a href="https://github.com/vitorglemos/">GitHub</a>
  </p>
  
  <p align="justify">
  MS degree 
  <br><br>
  Experience 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
