[
 {
  "username": "vitorglemos",
  "name": "Vitor G. Lemos",
  "userimg": "https://avatars.githubusercontent.com/u/31148456?v=4",
  "sort": "star",
  "order": "desc",
  "includeFork": true,
  "theme": "dark.css",
  "types": [
   "owner"
  ],
  "twitter": null,
  "linkedin": null,
  "medium": null,
  "dribbble": null
 }
]
